//created by UN: WWD & Board Loard Modref Dec 2016. Yalls welcome //

var subheadArray = ["Long slow dogfights that last forever",
                "Why did I say that? Sounds legit but like a summary of jr high ",
                "Like I could fart into a microphone and make a whole song out of fart drums",
                "un: WWD & Modref fucking rule",
                "Still portly because beer but goddamn I've been running like a fat gazelle lately",
                "They only charge you once to sign up and it includes everything, including physical.",
                "most people are super duper shitty and some of them also like videogames",
                "I only assume I was sniffing Strawberry Shortcake dolls.",
                "yelling 'avenge Harambe before you avenge me' while running away in short shorts.",
                "if you review my poast history, you can clearly see when I'm trying to become a subheading",
                "You're not going to find an affordable city without areas that look like a Fallout game.",
                "if I get struck by lightning again, I'm going to be beyond pissed.",
                "~ Hey Mister Tambourine man, 'splain a thing to me ~",
                "Of course Edge Day is on a Monday",
                "Kevin, you're what the French call A FUCKING NARC",
                "like watching paint dry",
                "except it's watching norms norm on normbook",
                "Guys, I posted it. I can't just 'take it back' now.",
                "I'm ficjibn drunk at a straight edge fest with Ben Henry and I can t wait to see floorpunch",
                "My entire life is already a satanic temple informational meeting.",
                "Did you know that Pringles was originally supposed to be a Tennis ball company?",
                "Hey I forgot to mention I goofed",
                "of course your llama lives in Brookline",
                "Choice Theory II: Choicer Theory",
                "The problem with unsocialized llamas is that they can be sexually aggressive - and nobody wants a-ram-a-llama-ding-dong.",
                "in case you're wondering, yes, the deer and I did match",
                "The best revenge is living well, but there are many, many other worthwhile forms of revenge as well.",
                "I immediately woke myself up with the sound of my own fart.",
                "MAKE JOE B'S PHONE NUMBER GREAT AGAIN",
                "All weed is shit to Jah.",
                "I still think about how much I hated that go to a child's birthday party mission. WTF was that lame shit?",
                "God, people are the fucking worst.",
                "but also fuck",
                "Total norm storm",
                "Hey man, I got vaginas for ears I can do anything.",
                "You can't just BUY a plush Rasta banana. You have to spend your life savings at a carnival to win one.",
                "he came through the square a few weeks ago on one of those razor scooters and did some sikk trixx, like bunny hops and curb stalls, while glowering at us fiercely",
                "Oh, hey, Secretary of State and Sack of Shit have the same acronym!",
                "Both of which is: S.O.S",
                "I'll send a sack of shit to the world",
                "I hope that someone gets my",
                "message in a butthole?",
                "I would at least wait until you've played magic tg",
                "Wanna hang out once a week but no more than that? - every dude ITT's entire outbound txt",
                "There is a front page article in today's Globe about how you are allowed to say bong instead of water pipe in a shop now.",
                "i would fuck him, no diggity",
                "he should probably be the site's mascot",
                "you hardly notice a couple of inches at all.",
                "The end game is you having coffee with a woman-high stack of weasels in an overcoat.",
                "When you need someone to have paid too much attention to the internet, I'm your man.",
                "hahahaha haha - GusGreece 26 London, UK",
                "The mild hallucinogens really helped!",
                "GET POOT TO POAST",
                "Lol Hitler is NOT a lady with a lovely flower. He's a dude with a wee dick and hidden ball and special p-hole.",
                "GET POOT TO POAST",
                "until such time as such is no longer relevant.",
                "STROSTON BONG",
                "RIP Butt Stuff",
                "Your escapades are THE REASON WE READ THIS BOARD",
                "Flavortown is a state of mind",
                "Yeah if you eat live lobster naked you definitely get hep C",
                "I heard Bernie wasn't named the winner of Nevada until today because Bill Clinton was hanging around at the caucus and finally just left.",
                "As I was glowering at him and getting closer, I see the look of scared panic in his wide eyes, and my empathy suddenly overwhelms me, and I feel just awful about myself and start sobbing and apologizing and the kid is looking at me like I am fucking insane.",
                "I have to truly hate someone's fucking guts before I can be the slightest bit mean to them.",
                "assemble a book an editor, it's could actually come to fruition.",
                "It's like the shocker, only worse.",
                "Hahaha butt pads!",
                "You can read that in Fraser voice I don't mind",
                "If I were a republican convention delegate, I would vote for a poem about Ronald Reagan",
                "eating at Applebees is just one of many harsher realities that comes with existing off the grid.",
                "aaaaaggghhh i need it in my mouth",
                "You know what they say. When life hands you dilemmas, make dilemmonade.",
                "omg Dick is so outstanding.",
                "still, if youre gonna do it you may as well fuckin do it",
                "Lol dont link me to rush or star trek again. :P",
                "The joys of being single are not experiencing those.",
                "I have a sex columnist.",
                "you have a family of bongs with very clever first, middle and last names, do not lie, sir.",
                "My apologies for being predictable.",
                "My apologies for being predictable.",
                "Rockabye",
                "he went on tinder dates with half the CDC",
                "Allah-Mode said:",
                "I've never spat at people while naked.",
                "*Immediately PMs about booking a basement show*",
                "The quality seems to be in the hand of the poker.",
                "I am genuinely pissed that that dude wasn't mortally wounded.",
                "I'm completely fine with day two of the convention's theme",
                "We Are Pokemon Go-ing To Help Working Families",
                "uuuugggghhhh this makes me so angry i could stick a remote up my butt",
                "recent polls show mcginty over toomey by 6 points, nice work neo",
                "it also shows clinton by 9 over trump in ever crucial PA",
                "in the future, we'll be taking our grandkids to art museums to see the new meme exhibit.",
                "recent polls show mcginty over toomey by 6 points, nice work neo",
                "it also shows clinton by 9 over trump in ever crucial PA",
                "oh man thoughts & prayers"];





                    var ri = Math.floor(Math.random() * subheadArray.length);
                    document.write(subheadArray[ri]);
                  
